#! /bin/sh

#  ____ ____ ____ ____ ____
# ||B |||S |||P |||W |||M ||
# ||__|||__|||__|||__|||__||
# |/__\|/__\|/__\|/__\|/__\|
#

# --- Custom ---

# Init shortcuts
sxhkd &
# Fix Java errors with bspwm
wname LG3D &
# Polybar
/home/puma/.config/polybar/launch.sh &
# Background
feh --bg-fill /home/puma/.config/feh/wallpaper
# Transparency
compton --config /home/puma/.config/compton/comptonrc &

# Windows Key as modifier
bscp config pointer_modifier mod1

# Programs as Floating Windows
bspc rule -a Caja desktop='^8' state=floating follow=on
bspc rule -a Gimp desktop='^8' state=floating follow=on

# --- Default ---

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
